name: Build Site

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Give build.sh execute permissions
        run: chmod +x ./build.sh

      - name: Run build script
        run: ./build.sh
